version: '3'
services:
  cassandra:
    image: cassandra:3.11
    volume: cassandradata:/var/lib/cassandra
  mail:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
  kuade:
    build: .
    volumes:
      - ./docker/data:/data
    ports:
      - "8000:8000"
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_SERVERS=cassandra
volumes:
  cassandradata:
