;; This is an attempt to define `Searchie` syntax in ABNF according to the grammar
;; defined in RFC 5234 (http://www.ietf.org/rfc/rfc5234.txt).
;;
;; You can try out this grammar using http://instaparse.mojombo.com/
;; To do so, in the lower right, click on Options and change `:input-format` to
;; ':abnf'. Then paste this entire ABNF document into the grammar entry box
;; (above the options). Then you can type or paste a sample TOML document into
;; the beige box on the left. Tada!

searchie   = *expression
expression = terms / terms condition term
terms = [include] *label predicate

;; include this term or negate them, if not specified parser should default to "+"
include  = "+" / "-";

label = label-meta / label-common
label-common  = text ":"
label-meta  = "@" text ":"

value = '#' text / text

;; predicate
predicate = predicate-compare / predicate-like / predicate-range / predicate-contains
predicate-like = "~" text
predicate-range = value "." "." value
predicate-contains = value
predicate-compare = predicate-op value
predicate-op = "=" / "<" / ">" / ">" "=" / "<" "=" / "<" ">" / "!" "="

;; conditions
condition = condition-and / condition-or / ws
condition-and = %x26  ; ampersand
condition-or  = %x7C  ; vertical-bar

;; chars that can't be used in query string wihout escape
keywords = kw-without-quotation / quotation-mark;
kw-without-quotation  = "." / "~" / "!" / "@" / "#" / "(" / ")" / "-" / "+" / "="
kw-without-quotation  =/ "<" / ">" / ":" / "\t" / "\r" / "\n" / " "
kw-wihout-quotation   =/ condition
;; whitespace
ws = *%x20

;; text
text = *basic-unescaped / quoted-text

quoted-text  = quotation-mark *quoted-chars quotation-mark / escape keywords
quoted-chars = basic-unescaped / kw-without-quotation

basic-unescaped = basic-punctuation / DIGIT / ALPHA / %x80-10FFFF;
escaped = escape kw-without-quotation;
basic-punctuation = %x2A / %x2F / %x3F / %x25 / %x27 / %x2C / %x3B

escape = %x5C                    ; backslash
quotation-mark = %x22            ; "

ALPHA = %x41-5A / %x61-7A ; A-Z / a-z
DIGIT = %x30-39 ; 0-9
